
mqtt:
  broker: "tcp://${MQTT_BROKER}:$MQTT_PORT"
  username: "${MQTT_USERNAME}"
  password: "${MQTT_PASSWORD}"

apiserver:
  url: "http://localhost:8080"
  username: "${API_USERNAME}"
  token: "${API_TOKEN}"
